IAM_URL="https://iam.api.cloud.yandex.net/iam/v1/tokens"
OAUTH_TOKEN="y0_AgAAAAAH61k_AATuwQAAAADUNud4kEOPQzbyR5WmRaCFe_Ei0NZc-mI"
VISION_URL="https://vision.api.cloud.yandex.net/vision/v1/batchAnalyze"
FOLDER_ID="b1g6ceqjotq7gji5heli"